(function(){
'use strict';
const app=document.getElementById('app');
const params=new URLSearchParams(location.search);
const dayNum=Math.max(7,Math.min(18,Number(String(params.get('day')||'7').replace(/[^0-9]/g,''))||7));
const sourceFile=dayNum===11?'korean_history2_day11_summary_fast_content.js':(dayNum>=12&&dayNum<=18?`korean_history2_day${dayNum-1}_fast_content.js`:`korean_history2_day${dayNum}_fast_content.js`);
const source=document.createElement('script');source.src=sourceFile;source.onload=boot;source.onerror=()=>fatal('복습 콘텐츠를 불러오지 못했습니다.');document.head.appendChild(source);
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fatal(msg){app.innerHTML=`<div class="shell"><div></div><section class="card start"><div class="lead">${esc(msg)}</div><button class="primary" id="hub">전체 Day 목록</button></section><div></div></div>`;document.getElementById('hub').onclick=()=>location.href='fast_index.html'}
function boot(){
 const C=window.HISTORY2_FAST_CONTENT;if(!C||!Array.isArray(C.questions))return fatal('콘텐츠 형식이 올바르지 않습니다.');
 const original=read(`history2-fast-day-${dayNum}`)||{};
 const profile=window.H2WeaknessProfile;
 let details=profile&&profile.weakFastDetail?profile.weakFastDetail(dayNum):[];
 if(!details.length){const seen={};(original.history||[]).forEach(e=>{if(e&&e.correct===false&&e.questionId)seen[e.questionId]=(seen[e.questionId]||0)+1});details=Object.entries(seen).map(([questionId,wrong])=>({questionId,wrong,score:wrong,concept:''}))}
 const byId=new Map(C.questions.map(q=>[q.id,q]));
 const queue=details.map(x=>({meta:x,item:byId.get(x.questionId)})).filter(x=>x.item).slice(0,12);
 if(!queue.length)return empty();
 const key=`history2-adaptive-fast-review-${dayNum}`;
 let state=read(key)||{phase:'intro',index:0,answered:null,repairOxMiss:false,lastDiagnosis:null,history:[],finishedAt:0,updatedAt:0};
 if(!Number.isInteger(state.index)||state.index<0)state.index=0;if(state.index>=queue.length)state.phase='done';
 function read(k){try{return JSON.parse(localStorage.getItem(k)||'null')}catch(_){return null}}
 function save(){state.updatedAt=Date.now();try{localStorage.setItem(key,JSON.stringify(state))}catch(_){}}
 function q(){return queue[state.index]&&queue[state.index].item}
 function shell(content){return `<div class="shell"><header class="top"><div><div class="kicker">적응형 취약 복습 · ${esc(C.unit)} · Day ${dayNum}</div><h1 class="title">${esc(C.title)}</h1></div><div class="progress"><b>${Math.min(state.index,queue.length)}</b> / ${queue.length}</div></header>${content}<footer class="foot">전체 문제를 다시 풀지 않고, 실제 오답만 복습합니다.</footer></div>`}
 function diagnosis(item,picked){const text=`${item.q||''} ${item.concept||''}`;let depth='D3',label='관계·순서 연결',skill='개념과 보기 연결';if(/옳지 않은|아닌 것은|잘못|구별|해당하지/.test(text)){depth='D4';label='보기 구별·문제 적용';skill='비슷한 보기 구별'}else if(/연도|시기|순서|직후|이후|이전|먼저|나중|몇 년|언제/.test(text)){skill='시기·순서 연결'}else if(/결과|배경|원인|영향|이어|계기|때문/.test(text)){skill='원인·결과 연결'}else if(/인물|누가|중심|주도|이끈|조합/.test(text)){skill='인물·활동 연결'}else if(/단체|기관|회의|정책|제도|사건|운동|무엇|특징|설명/.test(text)){depth='D2';label='뜻·핵심 사실';skill='핵심 개념·특징 확인'}const focus=String(item.recovery&&item.recovery.path&&item.recovery.path.at(-1)||item.concept||'핵심 개념');return{depth,label,skill,focus,picked:String(item.options&&item.options[picked]||''),message:`${item.concept}에서 ${skill} 단계만 다시 확인합니다.`}}
 function diagHtml(d){const rank={D1:1,D2:2,D3:3,D4:4}[d.depth]||3,steps=[['D1','대상 알아보기'],['D2','뜻·핵심 사실'],['D3','관계·순서 연결'],['D4','보기 구별·문제 적용']];return `<div class="diagnosis"><div class="diag-head"><b>이번 오답의 복구 지점</b><span class="badge">${esc(d.depth)} · ${esc(d.label)}</span></div><div class="diag-main">${esc(d.message)}</div><div class="ladder">${steps.map((s,i)=>`<div class="step ${i+1===rank?'on':''}">${s[0]}<br>${s[1]}</div>`).join('')}</div></div><div class="focus">이번에 복구할 것 · ${esc(d.focus)}</div>`}
 function render(){if(state.phase==='intro')return intro();if(state.phase==='repair')return repair();if(state.phase==='done')return done();question()}
 function intro(){const list=queue.slice(0,6).map((x,i)=>`<div class="weak-item"><b>${i+1}. ${esc(x.item.concept)}</b><span>${esc(x.item.branch)} · 이전 오답 ${x.meta.wrong||1}회</span></div>`).join('');app.innerHTML=shell(`<section class="card start"><div><div class="lead">틀렸던 문제만 다시 풉니다.</div><div class="sub">가장 많이 흔들린 문제부터 최대 ${queue.length}개만 복습합니다. 맞힌 문제는 다시 넣지 않습니다.</div></div><div class="weak-list">${list}</div><button class="primary" id="start">취약 문제 복습 시작</button><button class="secondary" id="hub">전체 Day 목록</button></section>`);document.getElementById('start').onclick=()=>{state.phase='question';save();render()};document.getElementById('hub').onclick=()=>location.href='fast_index.html'}
 function question(){const item=q();if(!item){state.phase='done';save();return render()}const answered=state.answered;const choices=item.options.map((o,i)=>`<button class="choice${answered==null?'':(i===item.answer?' correct':(i===answered?' wrong':''))}" data-i="${i}" ${answered==null?'':'disabled'}><span class="n">${i+1}</span><span>${esc(o)}</span></button>`).join('');let fb='';if(answered!=null){const good=answered===item.answer;fb=`<div class="feedback ${good?'good':'bad'}"><strong>${good?'복구 확인':'아직 이 지점이 흔들립니다'}</strong><span>${esc(good?item.why:state.lastDiagnosis.message)}</span></div>${good?'<button class="primary" id="next">다음 취약 문제 →</button>':''}`};app.innerHTML=shell(`<section class="card"><div class="qmeta"><span class="concept">${esc(item.branch)} · ${esc(item.concept)}</span><span>${state.index+1} / ${queue.length}</span></div><div class="qtext">${esc(item.q)}</div><div class="choices">${choices}</div>${fb}</section>`);app.querySelectorAll('.choice').forEach(b=>b.onclick=()=>answer(Number(b.dataset.i)));const n=document.getElementById('next');if(n)n.onclick=next;if(answered!=null&&answered!==item.answer)setTimeout(()=>{state.phase='repair';state.answered=null;save();render()},650)}
 function answer(i){const item=q();const correct=i===item.answer;state.answered=i;state.lastDiagnosis=correct?null:diagnosis(item,i);state.history.push({questionId:item.id,concept:item.concept,choice:i,correct,diagnosis:state.lastDiagnosis,at:Date.now()});save();render()}
 function repair(){const item=q(),r=item.recovery,d=state.lastDiagnosis||diagnosis(item,-1),path=(r.path||[]).map((p,i)=>`${i?'<i>→</i>':''}<span>${esc(p)}</span>`).join('');app.innerHTML=shell(`<section class="card">${diagHtml(d)}<div class="path">${path}</div><div class="clue">${esc(r.clue)}</div><div class="judge"><div class="judge-label">복구 확인 · 맞으면 O, 아니면 X</div><div class="judge-statement">${esc(r.ox.text)}</div><div class="ox"><button data-v="1"><strong>O</strong>맞다</button><button data-v="0"><strong>X</strong>아니다</button></div>${state.repairOxMiss?`<div class="correction">${esc(r.ox.correction||r.clue)}</div>`:''}</div></section>`);app.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>judge(b.dataset.v==='1'))}
 function judge(v){const item=q(),correct=v===!!item.recovery.ox.answer;state.history.push({questionId:item.id,concept:item.concept,repair:true,correct,diagnosis:state.lastDiagnosis,at:Date.now()});if(correct){state.phase='question';state.answered=null;state.repairOxMiss=false;save();render()}else{state.repairOxMiss=true;save();render()}}
 function next(){state.index++;state.phase=state.index>=queue.length?'done':'question';state.answered=null;state.lastDiagnosis=null;state.repairOxMiss=false;if(state.phase==='done')state.finishedAt=Date.now();save();render()}
 function done(){if(!state.finishedAt){state.finishedAt=Date.now();save()}app.innerHTML=shell(`<section class="card done"><h2>취약 문제 복습 완료</h2><div class="sub">이번 세션에서는 ${queue.length}개의 실제 오답만 다시 확인했습니다.</div><button class="primary" id="hub">전체 Day로 돌아가기</button><button class="secondary" id="again">이 복습 다시 하기</button></section>`);document.getElementById('hub').onclick=()=>location.href='fast_index.html';document.getElementById('again').onclick=()=>{state={phase:'intro',index:0,answered:null,repairOxMiss:false,lastDiagnosis:null,history:[],finishedAt:0,updatedAt:0};save();render()}}
 function empty(){app.innerHTML=`<div class="shell"><div></div><section class="card start"><div class="lead">지금 다시 풀 취약 문제가 없습니다.</div><div class="sub">이 Day에서 새 오답이 생기면 자동으로 복습 목록에 들어옵니다.</div><button class="primary" id="hub">전체 Day 목록</button></section><div></div></div>`;document.getElementById('hub').onclick=()=>location.href='fast_index.html'}
 render();
}
})();