(function(){
'use strict';
if(!window.H2ConceptDepth||typeof COURSE==='undefined'||typeof state==='undefined')return;
const mt=String(COURSE.meta&&COURSE.meta.id||'').match(/day(\d+)/i),DAYNUM=mt?Number(mt[1]):0;
if(!DAYNUM)return;
state.conceptDepthLog=state.conceptDepthLog||[];
const css=`.depth-card{max-width:840px;margin:auto}.depth-kicker{font-size:16px;font-weight:950;color:#64748b;letter-spacing:.025em;margin-bottom:9px}.depth-title{font-size:clamp(32px,4vw,44px);margin:0 0 9px;line-height:1.15}.depth-sub{font-size:18px;color:#59697d;font-weight:760;line-height:1.55;margin:0 0 15px}.depth-path{display:flex;gap:8px;flex-wrap:wrap;margin:10px 0 18px}.depth-path span{padding:8px 11px;border-radius:999px;background:#eef3f8;color:#64748b;font-size:15px;font-weight:900}.depth-path span.on{background:#eaf4fc;color:#2f6f9f}.depth-path span.fail{background:#fff2e4;color:#9a5c18}.depth-choice-grid{display:grid;gap:12px}.depth-choice{width:100%;min-height:60px;border:2px solid #dce4ee;border-radius:15px;background:#fff;padding:15px 17px;text-align:left;font:inherit;font-size:18px;font-weight:850;line-height:1.45}.depth-choice:hover{border-color:#a9c5dd}.depth-msg{min-height:28px;margin:12px 0 0;color:#9a5c18;font-size:16px;font-weight:850}.depth-msg.ok{color:#217a53}.depth-input{width:100%;height:68px;border:3px solid #d5dfeb;border-radius:17px;padding:0 16px;text-align:center;font:inherit;font-size:26px;font-weight:900}.depth-input:focus{outline:none;border-color:#4397d6;box-shadow:0 0 0 5px rgba(67,151,214,.12)}.depth-anchor{padding:19px;border-radius:18px;background:#eef5fb;border:1px solid #d6e5f1;margin:12px 0 16px}.depth-anchor b{display:block;font-size:27px;margin-bottom:6px}.depth-anchor p{margin:0;color:#52657a;line-height:1.55;font-size:18px;font-weight:760}.depth-note{font-size:15px;color:#738195;font-weight:800;margin-top:10px}`;
const st=document.createElement('style');st.id='conceptDepthStyles';st.textContent=css;document.head.appendChild(st);
function esc(v){return escapeHtml(v)}
function rt(p){return H2ConceptDepth.route(DAYNUM,p.id)}
function resetDepth(){runtime._depth=null}
function initDepth(p){if(runtime._depth)return runtime._depth;const r=rt(p);runtime._depth={phase:'concept-check',failed:[],baseLevel:null,msg:'',startedAt:Date.now(),misses:0,actions:0,route:r,inputTry:0,showAnswer:false};return runtime._depth}
function levelIndex(id){return {unit:0,root:1,branch:2,concept:3,keyword:4}[id]??0}
function activeLevel(s){if(s.phase.includes('concept'))return 'concept';if(s.phase.includes('branch'))return 'branch';if(s.phase.includes('root'))return 'root';if(s.phase.includes('unit'))return 'unit';if(s.phase==='keyword')return 'keyword';return 'concept'}
function pathHtml(s){const labels=[['unit','대단원'],['root','오늘 범위'],['branch','큰 가지'],['concept','세부 개념'],['keyword','핵심어']],cur=activeLevel(s);return `<div class="depth-path">${labels.map(([id,l])=>`<span class="${id===cur?'on':''} ${s.failed.includes(id)?'fail':''}">${l}</span>`).join('')}</div>`}
function choices(options,answer){return `<div class="depth-choice-grid">${(options||[]).map((x,i)=>`<button class="depth-choice" data-depth-choice="${i}" data-depth-answer="${esc(answer)}">${esc(x)}</button>`).join('')}</div>`}
function promptFor(s,r){if(s.phase==='concept-check')return ['이 문제와 가장 가까운 개념은 무엇인가요?','가까운 개념부터 확인합니다.',choices(r.conceptOptions,r.conceptTitle)];if(s.phase==='branch-check')return ['한 단계 위 큰 가지는?','세부 개념이 흔들리면 바로 위 큰 가지를 확인합니다.',choices(r.branchOptions,r.branchLabel)];if(s.phase==='root-check')return ['이 문제의 오늘 범위는?','큰 가지도 흔들리면 오늘 범위까지 올라갑니다.',choices(r.rootOptions,r.rootLabel)];if(s.phase==='unit-anchor')return ['가장 큰 지도부터 다시','여기부터는 알고 있다고 가정하지 않습니다.',`<div class="depth-anchor"><b>${esc(r.unitLabel)}</b><p>큰 지도 → 오늘 범위 → 큰 가지 → 세부 개념 순서로 다시 내려갑니다.</p></div><button class="primary" id="depthAnchorNext">여기서부터 다시 연결</button>`];if(s.phase==='descend-root')return ['오늘 범위 다시 연결','큰 지도 안에서 오늘 범위를 고릅니다.',choices(r.rootOptions,r.rootLabel)];if(s.phase==='descend-branch')return ['큰 가지 다시 연결',`<b>${esc(r.rootLabel)}</b> 안에서 맞는 가지를 고릅니다.`,choices(r.branchOptions,r.branchLabel)];if(s.phase==='descend-concept')return ['세부 개념 다시 연결',`<b>${esc(r.branchLabel)}</b> 안에서 이 문제의 개념을 고릅니다.`,choices(r.conceptOptions,r.conceptTitle)];const m=r.memory;if(m)return ['마지막은 직접 써서 고정',esc(m.prompt),`<input id="depthInput" class="depth-input" autocomplete="off" spellcheck="false" placeholder="핵심어 입력"><button class="primary" id="depthSubmit" style="margin-top:12px">입력 확인</button>${m.link?`<div class="depth-note">연결 힌트 · ${esc(m.link)}</div>`:''}`];return ['마지막 핵심 연결','이 문제의 세부 개념 이름을 직접 입력하세요.',`<input id="depthInput" class="depth-input" autocomplete="off" spellcheck="false" placeholder="개념 이름 입력"><button class="primary" id="depthSubmit" style="margin-top:12px">입력 확인</button>`]}
function renderDepthRepair(p){const s=initDepth(p),r=s.route;if(!r)return renderAnchorRepair(p);const [title,sub,body]=promptFor(s,r);return `<div class="depth-card"><div class="depth-kicker">어디부터 다시 연결할지 확인</div>${pathHtml(s)}<h2 class="depth-title">${title}</h2><p class="depth-sub">${sub}</p>${body}<div class="depth-msg ${s.msg==='연결됨'?'ok':''}">${esc(s.msg==='연결됨'?'연결됨':s.msg||'')}</div></div>`}
function isSame(a,b){return normalize(a)===normalize(b)}
function nextAfterKnown(s,level){s.baseLevel=s.baseLevel||level;s.msg='연결됨';setTimeout(()=>{s.msg='';if(level==='concept')s.phase='keyword';else if(level==='branch')s.phase='descend-concept';else if(level==='root')s.phase='descend-branch';else s.phase='descend-root';render()},350)}
function descendNext(s,phase){s.msg='연결됨';setTimeout(()=>{s.msg='';s.phase=phase;render()},350)}
function wrongUp(s,level,next){if(!s.failed.includes(level))s.failed.push(level);s.misses++;s.msg='여기서 흔들렸어요. 한 단계 위에서 다시 찾습니다.';setTimeout(()=>{s.msg='';s.phase=next;render()},450)}
function completeDepth(p){const s=runtime._depth,r=s.route;const entry={id:'cd-'+uid(),day:DAYNUM,problemId:p.id,at:Date.now(),baseLevel:s.baseLevel||'concept',failedLevels:[...s.failed],misses:s.misses||0,actions:s.actions||0,durationMs:Math.max(0,Date.now()-s.startedAt),metacogDepth:(typeof metacogFor==='function'?(metacogFor(p,runtime.answer)||{}).depth:(runtime.lastDiagnosis&&runtime.lastDiagnosis.depth)||'')||'',path:r.path};state.conceptDepthLog=state.conceptDepthLog||[];state.conceptDepthLog.push(entry);saveState();try{remotePatch({conceptDepthLog:state.conceptDepthLog})}catch(e){}runtime.feedbackStep++;resetDepth();render()}
function bindDepth(){const p=currentProblem(),s=runtime._depth;if(!s)return;document.querySelectorAll('[data-depth-choice]').forEach(b=>b.onclick=()=>{const r=s.route,v=b.textContent.trim(),ans=b.dataset.depthAnswer;s.actions++;if(isSame(v,ans)){if(s.phase==='concept-check')nextAfterKnown(s,'concept');else if(s.phase==='branch-check')nextAfterKnown(s,'branch');else if(s.phase==='root-check')nextAfterKnown(s,'root');else if(s.phase==='descend-root')descendNext(s,'descend-branch');else if(s.phase==='descend-branch')descendNext(s,'descend-concept');else if(s.phase==='descend-concept')descendNext(s,'keyword')}else{if(s.phase==='concept-check')wrongUp(s,'concept','branch-check');else if(s.phase==='branch-check')wrongUp(s,'branch','root-check');else if(s.phase==='root-check'){if(!s.failed.includes('root'))s.failed.push('root');s.misses++;s.baseLevel='unit';s.phase='unit-anchor';s.msg='';render()}else{s.misses++;s.msg='위에서 잡은 연결을 보고 다시 고르세요.';render()}}});const an=document.getElementById('depthAnchorNext');if(an)an.onclick=()=>{s.actions++;s.phase='descend-root';render()};const inp=document.getElementById('depthInput'),sub=document.getElementById('depthSubmit');const submit=()=>{const r=s.route,m=r.memory,v=String(inp&&inp.value||'').trim();if(!v)return;s.actions++;const accepted=m?[m.answer,...(m.accepted||[])]:[r.conceptTitle];if(accepted.some(x=>isSame(x,v))){s.msg='연결됨';setTimeout(()=>completeDepth(p),350)}else{s.misses++;s.inputTry++;if(s.inputTry===1)s.msg='힌트: '+(m&&m.hint||String(accepted[0]||'').slice(0,1)+'…');else s.msg='정답을 한 번 보고, 바로 다시 직접 입력하세요: '+accepted[0];render()}};if(sub)sub.onclick=submit;if(inp){setTimeout(()=>inp.focus(),40);inp.onkeydown=e=>{if(e.key==='Enter')submit()}}}
const baseReset=resetRuntimeForQuestion;resetRuntimeForQuestion=function(){resetDepth();return baseReset()};
const baseSteps=explanationSteps;explanationSteps=function(p){const s=baseSteps(p).filter(x=>x!=='depth-ladder');const i=s.indexOf('metacog');s.splice(i>=0?i+1:1,0,'depth-ladder');return s};
const priorRender=renderExplanation;renderExplanation=function(p){const steps=explanationSteps(p),kind=steps[Math.min(runtime.feedbackStep,steps.length-1)];if(kind==='depth-ladder')return `<div class="learn-grid">${renderPath(p)}<section class="panel feedback-screen"><div class="repair-card">${repairProgress(runtime.feedbackStep,steps.length)}${renderDepthRepair(p)}</div></section></div>`;return priorRender(p)};
const baseBind=bind;bind=function(){baseBind();bindDepth()};
render();
})();
