(function(){
'use strict';
const app=document.getElementById('app');
const params=new URLSearchParams(location.search);
const dayNum=Math.max(7,Math.min(18,Number(String(params.get('day')||'7').replace(/[^0-9]/g,''))||7));
const problemId=String(params.get('problem')||'').trim();
const gateUid=String(params.get('gateUid')||'').trim();
const returnUrl=String(params.get('return')||'pre_chapter_wrong_gate.html');
const sourceFile=dayNum===11?'korean_history2_day11_summary_fast_content.js':(dayNum>=12&&dayNum<=18?`korean_history2_day${dayNum-1}_fast_content.js`:`korean_history2_day${dayNum}_fast_content.js`);
let item=null,wrongAttempts=0,bookSeen=false,selected=null;

function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function shell(content){return `<div class="shell"><header class="top"><div><div class="kicker">이전 오답 복구 · Day ${dayNum}</div><h1 class="title">책을 찾아 스스로 해결하기</h1></div></header>${content}<footer class="foot">재오답에서는 정답과 해설을 바로 공개하지 않습니다.</footer></div>`}
function fatal(msg){app.innerHTML=shell(`<section class="card"><div class="qtext">${esc(msg)}</div><button class="primary" id="back">돌아가기</button></section>`);document.getElementById('back').onclick=()=>location.href=returnUrl}
function load(){const s=document.createElement('script');s.src=sourceFile;s.onload=boot;s.onerror=()=>fatal('문제 콘텐츠를 불러오지 못했습니다.');document.head.appendChild(s)}
function waitSystem(){return new Promise(resolve=>{if(window.H2WrongAnswerRegistry&&window.H2TextbookLocator)return resolve();let n=0;const t=setInterval(()=>{if((window.H2WrongAnswerRegistry&&window.H2TextbookLocator)||++n>120){clearInterval(t);resolve()}},50)})}
function registryRecord(){try{return window.H2WrongAnswerRegistry&&gateUid?H2WrongAnswerRegistry.get(gateUid):null}catch(_){return null}}
function pendingLookup(){try{return !!(window.H2WrongAnswerRegistry&&gateUid&&typeof H2WrongAnswerRegistry.needsBookLookup==='function'&&H2WrongAnswerRegistry.needsBookLookup(gateUid))}catch(_){return false}}
function locator(){const r=registryRecord();if(r&&r.locator)return Promise.resolve(r.locator);if(window.H2TextbookLocator&&H2TextbookLocator.get)return H2TextbookLocator.get(dayNum,problemId,item);return Promise.resolve(null)}
function rows(loc){const g=window.H2TextbookLocator&&H2TextbookLocator.guide?H2TextbookLocator.guide(loc,{includeKeywords:false}):null;if(!g)return '';let html=(g.rows||[]).filter(r=>r.label!=='찾아볼 말').map(r=>`<div class="book-row"><b>${esc(r.label)}</b><span>${esc(r.value)}</span></div>`).join('');if(loc&&loc.questionNo)html+=`<div class="book-row"><b>문제 위치</b><span>${esc(loc.questionNo)}번 주변</span></div>`;return html}
function mark(correct){try{if(window.H2WrongAnswerRegistry&&gateUid)return H2WrongAnswerRegistry.markGateAttempt(gateUid,correct,{bookUsed:bookSeen})}catch(_){}return null}
function renderQuestion(){selected=null;const choices=item.options.map((o,i)=>`<button class="choice" data-i="${i}"><span class="n">${i+1}</span><span>${esc(o)}</span></button>`).join('');app.innerHTML=shell(`<section class="card question-card"><div class="qmeta"><span>이전에 틀린 문제</span><span>교재 복구 관문</span></div><div class="qtext">${esc(item.q)}</div><div class="choices">${choices}</div></section>`);app.querySelectorAll('.choice').forEach(b=>b.onclick=()=>answer(Number(b.dataset.i)))}
function answer(i){if(selected!==null)return;selected=i;const correct=i===item.answer;if(correct)return success();wrongAttempts++;bookSeen=true;if(!pendingLookup())mark(false);showBook()}
async function showBook(){const loc=await locator();app.innerHTML=shell(`<section class="card"><div class="feedback bad"><strong>다시 틀렸습니다. 해설은 아직 보지 않습니다.</strong><span>책에서 근거를 직접 찾은 뒤 같은 문제를 다시 풀어보세요.</span></div><div style="display:grid;gap:10px;margin-top:18px;padding:20px;border:1px solid var(--line);border-radius:18px;background:var(--soft)">${rows(loc)||'<div class="book-row"><b>안내</b><span>현재 챕터의 해당 목록에서 찾아보세요.</span></div>'}</div><div class="correction" style="margin-top:16px">정답·해설·정답 핵심어는 지금 공개하지 않습니다. 책에서 관련 내용을 찾은 뒤 다시 판단합니다.</div><button class="primary" id="retry" style="margin-top:20px">책에서 찾았습니다 → 같은 문제 다시 풀기</button></section>`);if(!document.getElementById('h2FastBookGateStyle')){const style=document.createElement('style');style.id='h2FastBookGateStyle';style.textContent='.book-row{display:grid;grid-template-columns:110px minmax(0,1fr);gap:12px;font-size:19px;line-height:1.45}.book-row b{color:#55708f}.book-row span{font-weight:950;color:#173b60;word-break:keep-all}@media(max-width:650px){.book-row{grid-template-columns:85px 1fr;font-size:17px}}';document.head.appendChild(style)}document.getElementById('retry').onclick=()=>{bookSeen=true;renderQuestion()}}
function success(){mark(true);app.innerHTML=shell(`<section class="card done-card"><div class="done-title">오답 복구 완료</div><div class="score">${bookSeen?'책에서 근거를 찾아 같은 문제를 다시 맞혔습니다.':'이전 오답을 이번에는 바로 맞혔습니다.'}</div><div class="feedback good"><strong>확인</strong><span>${esc(item.why||'핵심 개념을 다시 확인했습니다.')}</span></div><button class="primary" id="go">다음으로 →</button></section>`);document.getElementById('go').onclick=()=>location.href=returnUrl}
async function boot(){const C=window.HISTORY2_FAST_CONTENT;if(!C||!Array.isArray(C.questions))return fatal('문제 데이터 형식이 올바르지 않습니다.');item=C.questions.find(q=>String(q&&q.id||'')===problemId)||null;if(!item)return fatal('지정된 오답 문제를 찾지 못했습니다.');await waitSystem();try{if(window.H2WrongAnswerRegistry)await H2WrongAnswerRegistry.sync()}catch(_){}if(pendingLookup()){bookSeen=true;showBook()}else renderQuestion()}
load();
})();
