(function(){
'use strict';
if(!window.H2FlowGuard||typeof COURSE==='undefined'||typeof state==='undefined'||typeof runtime==='undefined'||typeof render!=='function')return;
const G=H2FlowGuard;const m=String(COURSE.meta?.id||'').match(/day(\d+)/i);const DAY=m?Number(m[1]):0;const scope='day';let recovering=false,verifyTimer=null,lastTransition=null;
const allowedPhases=['intro','learn','closing','wrongbook','done'];const allowedModes=['question','correct','explain'];
function problem(){return COURSE.problems?.[state.problemIndex]||null}
function repairShape(){const fixes=[];const obj=(v)=>v&&typeof v==='object'&&!Array.isArray(v);if(!obj(state.problemStatus)){state.problemStatus={};fixes.push('problemStatus')}if(!Array.isArray(state.attempts)){state.attempts=[];fixes.push('attempts')}if(!obj(state.memoryLog)){state.memoryLog={};fixes.push('memoryLog')}if(!obj(state.wrongNotes)){state.wrongNotes={};fixes.push('wrongNotes')}if(!Array.isArray(state.reviewAttempts)){state.reviewAttempts=[];fixes.push('reviewAttempts')}if(!Array.isArray(state.reviewSessions)){state.reviewSessions=[];fixes.push('reviewSessions')}if(!obj(state.assignment)){state.assignment={requiredProblems:COURSE.problems.length,focus:''};fixes.push('assignment')}if(!Array.isArray(state.notes)){state.notes=[];fixes.push('notes')}if(!obj(state.sync)){state.sync={enabled:false,familyCode:'',configText:'',role:'student'};fixes.push('sync')}if(fixes.length)G.log('day-storage-repaired',{day:DAY,fields:fixes});return fixes}
function validate(){const e=[];if(!allowedPhases.includes(state.phase))e.push('invalid-phase');const i=Number(state.problemIndex);if(!Number.isInteger(i)||i<0||i>=COURSE.problems.length)e.push('invalid-problem-index');if(state.phase==='learn'&&!problem())e.push('missing-current-problem');if(!allowedModes.includes(runtime.mode))e.push('invalid-runtime-mode');if(runtime.mode==='explain'&&(!Number.isInteger(Number(runtime.feedbackStep))||Number(runtime.feedbackStep)<0))e.push('invalid-feedback-step');if(runtime.mode==='correct'&&problem()&&state.problemStatus?.[problem().id]?.status!=='mastered')e.push('correct-mode-without-mastery');return e}
function sanitize(reason){let changed=false;if(!allowedPhases.includes(state.phase)){state.phase='learn';changed=true}let i=Number(state.problemIndex);if(!Number.isInteger(i)){i=0;changed=true}i=Math.max(0,Math.min(COURSE.problems.length-1,i));if(i!==state.problemIndex){state.problemIndex=i;changed=true}if(!allowedModes.includes(runtime.mode)){runtime.mode='question';changed=true}if(runtime.mode==='explain'){let fs=Number(runtime.feedbackStep);if(!Number.isInteger(fs)||fs<0){runtime.feedbackStep=0;changed=true}if(problem()&&typeof explanationSteps==='function'){const max=Math.max(0,explanationSteps(problem()).length-1);if(runtime.feedbackStep>max){runtime.feedbackStep=max;changed=true}}if(runtime.answer==null){runtime.mode='question';runtime.feedbackStep=0;changed=true}}
 if(runtime.mode==='correct'&&problem()&&state.problemStatus?.[problem().id]?.status!=='mastered'){runtime.mode='question';changed=true}if(changed){try{baseSave(false)}catch(e){}G.log('day-state-sanitized',{day:DAY,reason,phase:state.phase,problemIndex:state.problemIndex,mode:runtime.mode})}return changed}
function depthRepairCompletedNow(){if(runtime.mode!=='explain'||runtime._depth!=null)return false;const logs=Array.isArray(state.conceptDepthLog)?state.conceptDepthLog:[];const last=logs[logs.length-1],p=problem();if(!last||!p||last.problemId!==p.id||Number(last.day)!==DAY)return false;const age=Date.now()-Number(last.at||0);return age>=0&&age<5000}
function routeDepthCompletionToRetry(){if(!depthRepairCompletedNow())return false;G.log('day-depth-direct-retry',{day:DAY,problemId:problem()?.id||null,feedbackStep:runtime.feedbackStep});if(typeof resetRuntimeForQuestion==='function')resetRuntimeForQuestion();else{runtime.mode='question';runtime.answer=null;runtime.feedbackStep=0;runtime.lastDiagnosis=null}return true}
function validDom(){if(runtime.route==='parent')return true;const root=document.getElementById('appMain');if(!root||!root.textContent.trim())return false;if(G.isVisibleAction(root))return true;if(root.querySelector('button[data-delay],.memory-answer-flash,.answer-flash,.feedback-card'))return true;if(state.phase==='done'||state.phase==='closing')return /완료|마무리/.test(root.textContent);return false}
function runtimeSnap(){return {route:runtime.route,mode:runtime.mode,answer:G.clone(runtime.answer),feedbackStep:runtime.feedbackStep,lastDiagnosis:G.clone(runtime.lastDiagnosis),repairAnswer:G.clone(runtime.repairAnswer),repairMessage:runtime.repairMessage,memoryInput:runtime.memoryInput,memoryMessage:runtime.memoryMessage,memoryPassed:runtime.memoryPassed,memoryTry:runtime.memoryTry,memoryShowAnswer:runtime.memoryShowAnswer,optionReviewIndex:runtime.optionReviewIndex,reviewIndex:runtime.reviewIndex,reviewInput:runtime.reviewInput,reviewMessage:runtime.reviewMessage,reviewPassed:runtime.reviewPassed,reviewTry:runtime.reviewTry,reviewStartedAt:runtime.reviewStartedAt,parentTab:runtime.parentTab}}
function currentTx(prev){const pid=problem()?.id||('phase-'+state.phase);if(prev&&prev.problemId===pid&&prev.txId)return prev.txId;return G.uid('d'+DAY+'-'+pid)}
function capture(){if(validate().length||!validDom())return;const prev=G.lastSafe(scope,DAY)||null;const snap={day:DAY,problemId:problem()?.id||null,phase:state.phase,problemIndex:state.problemIndex,mode:runtime.mode,feedbackStep:runtime.feedbackStep,txId:currentTx(prev),state:G.clone(state),runtime:runtimeSnap(),url:location.href};G.saveSafe(scope,DAY,snap);lastTransition={phase:state.phase,problemIndex:state.problemIndex,mode:runtime.mode,at:Date.now()}}
function restoreRuntime(s){const r=s?.runtime||{};Object.keys(r).forEach(k=>{if(k in runtime)runtime[k]=G.clone(r[k])})}
function recover(reason,error){if(recovering)return;recovering=true;try{const safe=G.lastSafe(scope,DAY);if(safe?.state){state=Object.assign(defaultState(),G.clone(safe.state));restoreRuntime(safe);sanitize('restore-safe');}else sanitize('fallback-'+reason);try{baseSave(false)}catch(e){}G.log('day-auto-recovery',{day:DAY,reason,error:String(error?.message||error||''),problemId:problem()?.id||null,phase:state.phase,mode:runtime.mode,txId:safe?.txId||null});baseRender();setTimeout(capture,30)}catch(e){G.log('day-recovery-failed',{day:DAY,reason,error:String(e?.message||e)})}finally{recovering=false}}
const baseRender=render;const baseSave=saveState;
try{const raw=typeof storageGet==='function'?storageGet(STORAGE_KEY):localStorage.getItem(STORAGE_KEY);if(raw){try{JSON.parse(raw)}catch(e){G.log('day-storage-invalid-json',{day:DAY,key:STORAGE_KEY});baseSave(false)}}}catch(e){}
repairShape();
saveState=function(remote=true){repairShape();const issues=validate();if(issues.length)sanitize('before-save:'+issues.join(','));return baseSave(remote)};
render=function(){if(recovering)return baseRender();repairShape();routeDepthCompletionToRetry();const issues=validate();if(issues.length)sanitize('before-render:'+issues.join(','));try{const r=baseRender();clearTimeout(verifyTimer);verifyTimer=setTimeout(()=>{if(!validDom())recover('dead-end-dom');else capture()},45);return r}catch(e){recover('render-exception',e)}};
window.addEventListener('error',e=>G.log('day-window-error',{day:DAY,message:e.message,source:e.filename,line:e.lineno,col:e.colno,problemId:problem()?.id||null,phase:state.phase,mode:runtime.mode}));
window.addEventListener('unhandledrejection',e=>G.log('day-unhandled-rejection',{day:DAY,reason:String(e.reason?.message||e.reason||''),problemId:problem()?.id||null}));
const root=document.getElementById('appMain');if(root)new MutationObserver(()=>{clearTimeout(verifyTimer);verifyTimer=setTimeout(()=>{if(!validDom())recover('mutation-dead-end');else capture()},70)}).observe(root,{childList:true,subtree:true});
setTimeout(()=>{const issues=validate();if(issues.length)sanitize('initial:'+issues.join(','));if(!validDom())recover('initial-dead-end');else capture()},80);
})();
