(function(){
'use strict';
if(!window.H2Policy)return;
const snap=H2Policy.parentSnapshot();if(!snap.events)return;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function pct(x){return x==null?'기록 대기':Math.round(x*100)+'%'}
function sec(ms){if(!ms)return '0초';return Math.max(1,Math.round(ms/1000))+'초'}
const style=document.createElement('style');style.textContent=`.pol-kpis{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin:14px 0}.pol-kpi{border:1px solid #e1e7ee;border-radius:15px;padding:14px;background:#fff}.pol-kpi span{display:block;color:#718095;font-size:11px;font-weight:850}.pol-kpi b{display:block;font-size:24px;margin-top:5px}.pol-table{width:100%;border-collapse:collapse;margin-top:14px;font-size:12px}.pol-table th,.pol-table td{padding:10px 8px;border-bottom:1px solid #e7ebf0;text-align:left;vertical-align:top}.pol-table th{color:#65748a;font-size:11px}.pol-badge{display:inline-block;padding:4px 7px;border-radius:999px;background:#eef4f9;color:#496a84;font-size:10px;font-weight:900}.pol-badge.up{background:#fff1df;color:#8d5719}.pol-badge.down{background:#eaf7ef;color:#27734f}.pol-note{color:#6f7e91;font-size:12px;font-weight:720;line-height:1.55;margin-top:10px}@media(max-width:720px){.pol-kpis{grid-template-columns:1fr}.pol-table{font-size:11px}}`;document.head.appendChild(style);
const mrows=snap.methods.map(m=>`<tr><td><b>${esc(m.label)}</b><br><small>${esc(m.id)}</small></td><td>${m.episodes}</td><td>${pct(m.immediate.rate)} <small>${m.immediate.n?`(${m.immediate.ok}/${m.immediate.n})`:''}</small></td><td>${pct(m.d1.rate)}</td><td>${pct(m.d3.rate)}</td><td>${pct(m.d7.rate)}</td><td>${sec(m.burden.durationMs)} / ${m.burden.actions.toFixed(1)}행동</td><td>${m.burden.retries.toFixed(1)} / ${m.burden.screens.toFixed(1)}</td></tr>`).join('');
const brows=snap.branches.slice(0,12).map(p=>{let badge='<span class="pol-badge">기록 축적</span>';if(p.needPrereq||p.longTermWeak)badge='<span class="pol-badge up">자동 강화</span>';else if(p.fadeLevel)badge=`<span class="pol-badge down">자동 축소 ${p.fadeLevel}단계</span>`;return `<tr><td><b>${esc(p.branchLabel)}</b></td><td>${badge}</td><td>${esc(p.selectedLabel)}</td><td>${esc(p.spacingMode)}</td><td>${esc(p.reason)}</td></tr>`}).join('');
const html=`<section class="section"><h2>개인화 보정 정책 · 효과 대비 행동량</h2><div class="desc">같은 학생의 같은 큰 가지에서 보정 방법별 효과와 부담을 누적합니다. 효과가 비슷하면 더 짧은 방법을 우선하고, 3·7일 유지가 안정되면 보조 발판부터 줄입니다.</div><div class="pol-kpis"><div class="pol-kpi"><span>비교 가능한 개입 기록</span><b>${snap.events}</b></div><div class="pol-kpi"><span>자동 축소 중인 가지</span><b>${snap.fadeCount}</b></div><div class="pol-kpi"><span>자동 강화 중인 가지</span><b>${snap.strengthenCount}</b></div></div><div style="overflow:auto"><table class="pol-table"><thead><tr><th>보정 방법</th><th>사건</th><th>직후</th><th>1일</th><th>3일</th><th>7일</th><th>평균 시간/행동</th><th>재시도/추가 화면</th></tr></thead><tbody>${mrows}</tbody></table></div>${brows?`<h3 style="margin-top:22px">가지별 자동 결정</h3><div style="overflow:auto"><table class="pol-table"><thead><tr><th>큰 가지</th><th>상태</th><th>우선 개입</th><th>회상 간격</th><th>자동 결정 근거</th></tr></thead><tbody>${brows}</tbody></table></div>`:''}<div class="pol-note">개념 뎁스 복구는 오답의 출발점을 찾는 핵심 절차라 자동으로 제거하지 않습니다. 축소 대상은 선행 프리체크·추가 반복오류 보정·일상 간격 회상 같은 보조 발판입니다. 간격 회상의 ‘직후’는 원문 재도전 대신 첫 회상 시도의 성공 여부를 사용합니다.</div></section>`;
const foot=document.querySelector('.foot,.footer');if(foot)foot.insertAdjacentHTML('beforebegin',html);else{const c=document.getElementById('content')||document.querySelector('.wrap')||document.body;c.insertAdjacentHTML('beforeend',html)}
})();
