(function(){
'use strict';
if(!window.H2Risk||typeof COURSE==='undefined'||typeof state==='undefined'||typeof renderLearn!=='function')return;
const mt=String(COURSE.meta&&COURSE.meta.id||'').match(/day(\d+)/i),DAYNUM=mt?Number(mt[1]):0;if(!DAYNUM)return;
state.policyStabilityLog=state.policyStabilityLog||[];state.riskPredictionLog=state.riskPredictionLog||[];state.proactiveMicrocheckLog=state.proactiveMicrocheckLog||[];state.riskCalibrationLog=state.riskCalibrationLog||[];
const css=`.risk-micro{max-width:720px;margin:auto}.risk-micro .k{font-size:12px;font-weight:950;color:#66758a;letter-spacing:.04em;margin-bottom:9px}.risk-micro h2{font-size:clamp(27px,4vw,39px);line-height:1.16;margin:0 0 9px}.risk-micro p{color:#59697d;font-weight:760;line-height:1.55;margin:0 0 15px}.risk-micro .tiny{display:inline-block;padding:6px 9px;border-radius:999px;background:#eef4f9;color:#496b88;font-size:11px;font-weight:900;margin-bottom:12px}.risk-micro input{width:100%;height:62px;border:3px solid #d5dfeb;border-radius:17px;padding:0 16px;text-align:center;font:inherit;font-size:23px;font-weight:900}.risk-micro .choices{display:grid;gap:10px}.risk-micro .choice{width:100%;padding:14px;border:2px solid #dce4ee;border-radius:15px;background:#fff;text-align:left;font:inherit;font-weight:850;font-size:16px}.risk-micro .msg{min-height:23px;margin-top:10px;color:#87571c;font-size:14px;font-weight:850}.risk-micro .msg.ok{color:#217a53}`;
const st=document.createElement('style');st.id='policyRiskDayStyles';st.textContent=css;document.head.appendChild(st);
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function norm(v){return String(v||'').replace(/[\s·.,()\-_/]/g,'').toLowerCase()}
function resetRisk(){runtime._riskMicro=null;runtime._riskMicroDoneFor=null;runtime._riskQuestionStartedAt=null}
function initMicro(p){if(runtime._riskMicro&&runtime._riskMicro.problemId===p.id)return runtime._riskMicro;if(runtime._riskMicroDoneFor===p.id)return null;const q=H2Risk.startMicro(DAYNUM,p.id);if(!q)return null;runtime._riskMicro={problemId:p.id,...q,actions:0,misses:0,firstCorrect:null,msg:'',done:false};return runtime._riskMicro}
function renderMicro(p){const s=initMicro(p);if(!s)return '';const c=s.candidate;if(c.kind==='branch-choice'){return `<div class="risk-micro"><div class="k">문제 전에 연결 하나만</div><span class="tiny">10~20초</span><h2>${esc(c.prompt)}</h2><p>하나만 고르면 바로 원문 문제로 갑니다.</p><div class="choices">${(c.options||[]).map((x,i)=>`<button class="choice" data-risk-choice="${i}">${esc(x)}</button>`).join('')}</div><div class="msg ${s.msg==='연결됨'?'ok':''}">${esc(s.msg)}</div></div>`}return `<div class="risk-micro"><div class="k">문제 전에 연결 하나만</div><span class="tiny">10~20초</span><h2>${esc(c.prompt)}</h2><p>짧게 떠올리고 바로 원문 문제로 갑니다.</p><input id="riskMicroInput" autocomplete="off" spellcheck="false" placeholder="핵심어 입력"><button class="primary" id="riskMicroSubmit" style="margin-top:11px">입력 확인</button><div class="msg ${s.msg==='연결됨'?'ok':''}">${esc(s.msg)}</div></div>`}
function finishMicro(s,ok){s.msg='연결됨';s.done=true;H2Risk.completeMicro(DAYNUM,s.log.id,{actions:s.actions,misses:s.misses,firstCorrect:s.firstCorrect});try{const fresh=H2Risk.read(DAYNUM);state.policyStabilityLog=fresh.policyStabilityLog||[];state.riskPredictionLog=fresh.riskPredictionLog||[];state.proactiveMicrocheckLog=fresh.proactiveMicrocheckLog||[];state.riskCalibrationLog=fresh.riskCalibrationLog||[];saveState(false)}catch(e){}render();setTimeout(()=>{runtime._riskMicro=null;runtime._riskMicroDoneFor=s.problemId;runtime._riskQuestionStartedAt=null;render()},320)}
function bindMicro(){const s=runtime._riskMicro;if(!s||s.done)return;document.querySelectorAll('[data-risk-choice]').forEach(b=>b.onclick=()=>{s.actions++;const v=b.textContent.trim(),ok=norm(v)===norm(s.candidate.answer);if(s.firstCorrect===null)s.firstCorrect=ok;if(ok)finishMicro(s,true);else{s.misses++;s.msg='큰 가지를 한 번 더 확인하세요.';render()}});const inp=document.getElementById('riskMicroInput'),btn=document.getElementById('riskMicroSubmit');const run=()=>{const v=String(inp?.value||'').trim();if(!v)return;s.actions++;const ok=(s.candidate.accepted||[s.candidate.answer]).some(x=>norm(x)===norm(v));if(s.firstCorrect===null)s.firstCorrect=ok;if(ok)finishMicro(s,true);else{s.misses++;s.msg=s.misses===1&&s.candidate.hint?'힌트 · '+s.candidate.hint:'핵심어를 다시 짧게 입력하세요.';if(inp)inp.value='';render()}};if(btn)btn.onclick=run;if(inp){setTimeout(()=>inp.focus(),40);inp.onkeydown=e=>{if(e.key==='Enter')run()}}}
// A proactive microcheck replaces the older automatic precheck for that one problem.
if(window.H2LearningEffect&&typeof H2LearningEffect.shouldPrecheck==='function'){
 const prev=H2LearningEffect.shouldPrecheck;H2LearningEffect.shouldPrecheck=function(day,pid,storage,now){if(Number(day)===DAYNUM&&runtime._riskMicroDoneFor===pid)return {eligible:false,reason:'proactive-microcheck-already-served'};return prev(day,pid,storage,now)}
}
const baseRenderLearn=renderLearn;
renderLearn=function(){const p=currentProblem();if(runtime.mode==='question'&&!H2Risk.isImmediateRetry(DAYNUM,p.id)){const html=renderMicro(p);if(html)return `<div class="learn-grid">${renderPath(p)}<section class="panel feedback-screen">${html}</section></div>`}const html=baseRenderLearn();if(runtime.mode==='question'&&String(html).includes('question-panel')&&!runtime._riskQuestionStartedAt)runtime._riskQuestionStartedAt=Date.now();return html};
const baseBind=bind;bind=function(){baseBind();bindMicro()};
const baseReset=resetRuntimeForQuestion;resetRuntimeForQuestion=function(){resetRisk();return baseReset()};
const baseCheck=checkAnswer;checkAnswer=function(){const p=currentProblem(),before=(state.attempts||[]).length,start=runtime._riskQuestionStartedAt||Date.now();baseCheck();const a=(state.attempts||[]).length>before?(state.attempts||[])[(state.attempts||[]).length-1]:null;if(!a)return;a.responseTimeMs=Math.max(0,Number(a.at||Date.now())-start);const out=H2Risk.evaluateAttempt(DAYNUM,p.id,a);try{const fresh=H2Risk.read(DAYNUM);state.policyStabilityLog=fresh.policyStabilityLog||[];state.riskPredictionLog=fresh.riskPredictionLog||[];state.proactiveMicrocheckLog=fresh.proactiveMicrocheckLog||[];state.riskCalibrationLog=fresh.riskCalibrationLog||[];saveState(false);if(typeof remotePatch==='function')remotePatch({attempts:state.attempts,policyStabilityLog:state.policyStabilityLog,riskPredictionLog:state.riskPredictionLog,proactiveMicrocheckLog:state.proactiveMicrocheckLog,riskCalibrationLog:state.riskCalibrationLog})}catch(e){}runtime._riskQuestionStartedAt=null};
render();
})();
