(function(){
'use strict';
if(!window.H2SessionLoad)return;
const css=`.session-load-parent{margin:22px 0;padding:20px;border:1px solid #dbe4ee;border-radius:18px;background:#fff}.session-load-parent h2{margin:0 0 8px;font-size:22px}.session-load-parent p{margin:0 0 14px;color:#66758a;line-height:1.55}.sl-kpis{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:10px;margin:14px 0}.sl-kpi{padding:13px;border-radius:14px;background:#f5f8fb}.sl-kpi span{display:block;font-size:11px;font-weight:850;color:#6b788a}.sl-kpi b{display:block;font-size:22px;margin-top:4px}.sl-table{width:100%;border-collapse:collapse;font-size:13px}.sl-table th,.sl-table td{padding:9px;border-bottom:1px solid #e7edf3;text-align:left;vertical-align:top}.sl-table .sub{display:block;color:#7a8797;font-size:11px;margin-top:3px}.sl-on{font-weight:900;color:#9a3f3f}.sl-off{font-weight:900;color:#2a7356}.sl-note{font-size:12px;color:#758295;line-height:1.55;margin-top:12px}@media(max-width:760px){.sl-kpis{grid-template-columns:repeat(2,1fr)}}`;
const st=document.createElement('style');st.id='sessionLoadParentStyles';st.textContent=css;document.head.appendChild(st);
function pct(v){return v==null?'-':Math.round(Number(v)*100)+'%'}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function dt(ms){if(!ms)return '-';try{return new Date(ms).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})}catch(e){return '-'}}
const s=H2SessionLoad.parentSnapshot(),c=s.current,a=s.aggregate;
function sigText(x){const sig=x.overloadSignals||{},parts=[];if(sig.wrong?.streak>=2)parts.push(`연속 오답 ${sig.wrong.streak}`);if(sig.deep?.n>=1)parts.push(`깊은 복구 ${sig.deep.n}`);if(sig.slow?.available&&sig.slow.score>0)parts.push('응답 지연');if(sig.fast?.available&&sig.fast.score>0)parts.push('빠른 추측');if(sig.burden?.score>=.55)parts.push('추가 행동 누적');return parts.length?parts.join(' · '):'뚜렷한 과부하 신호 없음'}
const rows=s.rows.map(x=>`<tr><td>${esc(dt(x.startedAt))}<span class="sub">${x.attempts}문항 · 정답 ${x.correct}</span></td><td>${x.extraActions}/${x.budgetActions}<span class="sub">화면 ${x.extraScreens}/${x.budgetScreens}</span></td><td>${Number(x.overloadScore||0).toFixed(2)}<span class="sub">${esc(sigText(x))}</span></td><td>${x.suppressedCount}<span class="sub">${esc(Object.entries(x.suppressedByKind||{}).map(([k,v])=>`${k} ${v}`).join(' · ')||'-')}</span></td><td>${x.anchorsServed}<span class="sub">이후 정답률 ${pct(x.postAnchorAccuracy)}</span></td><td>${x.overloadActive?'<span class="sl-on">억제 중</span>':'<span class="sl-off">일반 흐름</span>'}<span class="sub">과부하 주기 ${x.cycles}</span></td></tr>`).join('');
const html=`<section class="session-load-parent"><h2>세션 인지 부하 · 개입 예산</h2><p>개별 보정이 효과적이어도 한 세션의 추가 화면이 누적되면 비필수 발판부터 줄입니다. 실제 오답 뒤 메타인지와 개념 뎁스 복구는 항상 유지됩니다.</p><div class="sl-kpis"><div class="sl-kpi"><span>현재 추가 행동</span><b>${c.extraActions}/${c.budgetActions}</b></div><div class="sl-kpi"><span>현재 추가 화면</span><b>${c.extraScreens}/${c.budgetScreens}</b></div><div class="sl-kpi"><span>억제한 비필수 개입</span><b>${c.suppressedCount}</b></div><div class="sl-kpi"><span>재진입 연결</span><b>${c.anchorsServed}</b></div><div class="sl-kpi"><span>재진입 후 정답률</span><b>${pct(c.postAnchorAccuracy)}</b></div><div class="sl-kpi"><span>최근 세션 과부하 발생</span><b>${a.overloadSessions}/${a.sessions}</b></div></div><div style="overflow:auto"><table class="sl-table"><thead><tr><th>세션</th><th>추가 행동/화면</th><th>과부하 신호</th><th>억제</th><th>최소 재진입</th><th>현재 상태</th></tr></thead><tbody>${rows||'<tr><td colspan="6">아직 세션 기록이 없습니다.</td></tr>'}</tbody></table></div><div class="sl-note">응답시간 신호는 개인 기준 표본이 6개 이상일 때만 사용합니다. 과부하가 높으면 선제 마이크로 체크·자동 프리체크·추가 패턴 보정·선행 핵심어 같은 비필수 발판을 잠시 억제하고, 필요하면 다음 새 문제 전에 기존 DB 핵심어 1개만 확인합니다. 응답과 정답이 2~3문항 안정되면 자동 해제합니다.</div></section>`;
const foot=document.querySelector('.foot,.footer');if(foot)foot.insertAdjacentHTML('beforebegin',html);else{const ctn=document.getElementById('content')||document.querySelector('.wrap')||document.body;ctn.insertAdjacentHTML('beforeend',html)}
})();
