(function(){
'use strict';
if(!window.H2SessionResume||typeof COURSE==='undefined'||typeof state==='undefined'||typeof nextProblem!=='function')return;
const mt=String(COURSE.meta&&COURSE.meta.id||'').match(/day(\d+)/i),DAYNUM=mt?Number(mt[1]):0;if(!DAYNUM)return;
const css=`.resume-end-card{width:min(720px,100%);margin:auto;text-align:center;padding:34px 28px}.resume-end-card .ey{font-size:12px;font-weight:950;color:#6c788a;margin-bottom:12px}.resume-end-card h1{font-size:clamp(40px,6vw,66px);letter-spacing:-.055em;margin:0 0 14px}.resume-end-card .next{margin:18px auto;padding:18px;border-radius:18px;background:#f4f7fb;border:1px solid #dfe6ef;max-width:560px}.resume-end-card .next span{display:block;color:#718095;font-size:12px;font-weight:900;margin-bottom:6px}.resume-end-card .next b{font-size:clamp(22px,3vw,30px)}.resume-end-card p{color:#6c788a;font-weight:760;line-height:1.55}`;
const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function endHtml(t){const key=t.anchor?.keyword||t.anchor?.answer||'';return `<section class="panel resume-end-card"><div class="ey">오늘 학습</div><h1>오늘은 여기까지</h1><p>지금 문제까지 연결했습니다.</p><div class="next"><span>다음 시작 핵심</span><b>${esc(key)}</b></div><button class="primary ok" id="resumeEndReturn">오늘 마치기</button></section>`}
const params=new URLSearchParams(location.search),resumeId=params.get('token')||'',resumePid=params.get('problem')||'';
if(params.get('sessionResume')==='1'&&resumeId&&resumePid){const i=COURSE.problems.findIndex(p=>p.id===resumePid);if(i>=0){state.phase='learn';state.problemIndex=i;runtime.mode='question';runtime.answer=null;runtime._sessionResumeTokenId=resumeId;runtime._sessionEndToken=null;if(typeof resetRuntimeForQuestion==='function')resetRuntimeForQuestion();if(typeof saveState==='function')saveState(false);H2SessionResume.markResumeStarted(resumeId)}}
const baseRenderLearn=renderLearn;renderLearn=function(){if(runtime._sessionEndToken)return endHtml(runtime._sessionEndToken);return baseRenderLearn()};
const baseNext=nextProblem;nextProblem=function(){const p=currentProblem();if(runtime.mode==='correct'&&state.problemIndex<COURSE.problems.length-1){const next=COURSE.problems[state.problemIndex+1],planned=Number(state.assignment?.requiredProblems||COURSE.problems.length),remaining=COURSE.problems.length-(state.problemIndex+1),e=H2SessionResume.evaluate(DAYNUM,p.id,next.id,planned,remaining);const t=H2SessionResume.createToken(e);if(t){state.problemIndex++;state.phase='learn';if(typeof resetRuntimeForQuestion==='function')resetRuntimeForQuestion();if(typeof saveState==='function')saveState(false);runtime._sessionEndToken=t;render();return}}return baseNext()};
const baseBind=bind;bind=function(){baseBind();const b=document.getElementById('resumeEndReturn');if(b)b.onclick=()=>{const ret=(typeof FLOW_RETURN!=='undefined'&&FLOW_RETURN)||'korean_history2_unit1_student_metacog_flow.html';try{location.href=new URL(ret,location.href).href}catch(e){location.href=ret}}};
const baseCheck=checkAnswer;checkAnswer=function(){const before=(state.attempts||[]).length;baseCheck();if(!runtime._sessionResumeTokenId)return;const a=(state.attempts||[]).length>before?(state.attempts||[])[(state.attempts||[]).length-1]:null;if(a)H2SessionResume.recordTargetAttempt(runtime._sessionResumeTokenId,!!a.correct)};
render();
})();
