(function(g){
'use strict';
if(g.H2WeaknessProfile)return;
const S={1:'history2-day1-original-mastery-v2',2:'history2-day2-attention-mastery-v2',3:'history2-day3-terms-mastery-v1',4:'history2-day4-terms-mastery-v1',5:'history2-day5-terms-mastery-v1',6:'history2-day6-unit-review-v1'};
const U={1:'Ⅰ 일제 식민 통치와 민족 운동',2:'Ⅰ 일제 식민 통치와 민족 운동',3:'Ⅰ 일제 식민 통치와 민족 운동',4:'Ⅰ 일제 식민 통치와 민족 운동',5:'Ⅰ 일제 식민 통치와 민족 운동',6:'Ⅰ 일제 식민 통치와 민족 운동',7:'Ⅱ 대한민국의 발전',8:'Ⅱ 대한민국의 발전',9:'Ⅱ 대한민국의 발전',10:'Ⅱ 대한민국의 발전',11:'Ⅱ 대한민국의 발전',12:'Ⅲ 오늘날의 대한민국',13:'Ⅲ 오늘날의 대한민국',14:'Ⅲ 오늘날의 대한민국',15:'Ⅲ 오늘날의 대한민국',16:'단원별 TEST',17:'단원별 TEST',18:'단원별 TEST'};
const T={1:'01 일제의 식민지 통치 정책',2:'02 3·1 운동과 대한민국 임시 정부',3:'03 민족 운동의 전개와 분화',4:'04 사회·문화의 변화와 대중 운동',5:'05 독립 국가 건설 노력',6:'대단원 I 마무리',7:'06 냉전 체제와 대한민국 정부 수립',8:'07 6·25 전쟁과 남북 분단의 고착화',9:'08 민주화를 위한 노력',10:'09 산업화의 성과와 사회·문화의 변화',11:'대단원 II 마무리',12:'10 6월 민주 항쟁 이후의 민주화 과정',13:'11 외환 위기 극복과 사회·문화의 변동',14:'12 한반도 분단 극복과 동아시아 평화를 위한 노력',15:'대단원 III 마무리',16:'TEST 01~04 · 일제 식민 통치와 민족 운동',17:'TEST 05~08 · 정부 수립부터 민주화',18:'TEST 09~12 · 산업화부터 평화 노력'};
function j(k){try{return JSON.parse(localStorage.getItem(k)||'null')}catch(_){return null}}
function add(map,k,w,meta){if(!k||!(w>0))return;const x=map[k]||(map[k]={score:0,count:0,days:{},examples:[]});x.score+=w;x.count++;if(meta.day)x.days[meta.day]=1;if(meta.example&&x.examples.length<4&&!x.examples.includes(meta.example))x.examples.push(meta.example)}
function fastQuestionStats(s){const out={};(s.history||[]).forEach(e=>{if(!e||!e.questionId)return;const x=out[e.questionId]||(out[e.questionId]={wrong:0,last:null,concept:e.concept||'',branch:e.branch||'',depth:'',skill:''});if(e.correct===false){x.wrong++;if(e.diagnosis){x.depth=e.diagnosis.depth||x.depth;x.skill=e.diagnosis.skill||x.skill}}x.last=e});(s.repairLog||[]).forEach(e=>{if(!e||!e.questionId)return;const x=out[e.questionId]||(out[e.questionId]={wrong:0,last:null,concept:e.concept||'',branch:e.branch||'',depth:'',skill:''});if(e.correct===false)x.repairMiss=(x.repairMiss||0)+1;if(e.diagnosis){x.depth=e.diagnosis.depth||x.depth;x.skill=e.diagnosis.skill||x.skill}});return out}
function build(){const depth={},concept={},unit={},day={};
for(let d=1;d<=6;d++){const s=j(S[d])||{};Object.entries(s.wrongNotes||{}).forEach(([pid,w])=>{const m=w&&w.metacog||{},n=Math.max(1,Number(w&&w.wrongCount||1)),mastered=!!(s.problemStatus&&s.problemStatus[pid]&&s.problemStatus[pid].status==='mastered'),weight=n*(mastered?0.35:1),meta={day:d,example:w&&w.title||m.problemTitle||''};add(unit,U[d],weight,meta);add(depth,m.depth||m.metacogDepth||'미분류',weight,meta);add(concept,m.conceptTitle||m.branchLabel||w&&w.title||'미분류',weight,meta);add(day,'Day '+d,weight,meta)});(s.conceptDepthLog||[]).slice(-20).forEach(e=>{const meta={day:d,example:e.problemTitle||e.conceptTitle||''};add(depth,e.depth||e.metacogDepth||'미분류',0.25,meta)})}
for(let d=7;d<=18;d++){const s=j('history2-fast-day-'+d)||{},stats=fastQuestionStats(s);Object.values(stats).forEach(x=>{if(!x.wrong)return;const resolved=!!(x.last&&x.last.correct===true),weight=x.wrong*(resolved?0.35:1)+(x.repairMiss||0)*0.5,meta={day:d,example:x.concept||x.branch||''};add(unit,U[d],weight,meta);add(depth,x.depth||'미분류',weight,meta);add(concept,x.concept||x.branch||'미분류',weight,meta);add(day,'Day '+d,weight,meta)})}
function top(map,n){return Object.entries(map).map(([name,v])=>({name,...v,score:Math.round(v.score*100)/100,dayCount:Object.keys(v.days).length})).sort((a,b)=>b.score-a.score||b.count-a.count).slice(0,n)}
return{updatedAt:Date.now(),topDepth:top(depth,4),topConcept:top(concept,8),topUnit:top(unit,4),topDay:top(day,18),raw:{depth,concept,unit,day}}}
function dayDone(d){if(d<=6){const s=j(S[d])||{};return !!(s.finishedAt||s.phase==='done')}const s=j('history2-fast-day-'+d)||{};return !!(s.finishedAt||s.phase==='done')}
function weakFastDetail(d){const s=j('history2-fast-day-'+d)||{},stats=fastQuestionStats(s),rows=Object.entries(stats).filter(([,x])=>x.wrong>0).map(([questionId,x])=>({questionId,...x,score:x.wrong*((x.last&&x.last.correct===true)?0.35:1)+(x.repairMiss||0)*0.5})).sort((a,b)=>b.score-a.score||b.wrong-a.wrong);return rows}
function recommend(){const p=build(),weak=(p.topDay||[]).find(x=>x.score>=0.5);if(weak){const m=String(weak.name).match(/(\d+)/),d=m?Number(m[1]):0;if(d>=1&&d<=6)return{type:'review',day:d,title:'Day 1~6 취약 문제 복습',detail:`${p.topDepth[0]?.name||'개념'} 단계와 반복 오답을 먼저 복구합니다.`,href:'korean_history2_unit1_adaptive_review_metacog_flow.html',score:weak.score};if(d>=7&&d<=18){const f=weakFastDetail(d)[0];return{type:'review',day:d,title:`Day ${d} 취약 문제만 복습`,detail:f&&f.concept?`${f.concept}부터 다시 확인합니다.`:`${T[d]}에서 틀린 문제만 다시 풉니다.`,href:`adaptive_fast_review.html?day=${d}`,score:weak.score}}}
for(let d=1;d<=18;d++)if(!dayDone(d))return{type:'progress',day:d,title:`Day ${d} 이어서 학습`,detail:T[d],href:d<=6?`korean_history2_day${d}_student_flow_app.html`:`fast_day.html?day=${d}`,score:0};return{type:'complete',day:18,title:'18일 학습 완료',detail:'누적 취약점이 생기면 복습이 다시 우선 추천됩니다.',href:'fast_index.html',score:0}}
function get(){const p=build();try{localStorage.setItem('history2-weakness-profile-v1',JSON.stringify(p))}catch(_){}return p}
g.H2WeaknessProfile={get,build,recommend,weakFastDetail,dayDone};
})(window);